#! /bin/bash

git pull
git submodule foreach --recursive git checkout master
git submodule foreach --recursive git pull
git submodule foreach --recursive git reset --hard origin/master
git submodule update --init --recursive
git pull --recurse-submodules


echo 'Pull OK'
