#! /bin/bash

script_dir=$(dirname "$(dirname "$(realpath "$0")")")

cd "$script_dir" || (echo "FAIL" && exit 0)

echo "You are in:"
pwd

# Go up one level
parent_dir=$(dirname "$script_dir")

is_app_dir() {
  local dir_name="$1"
  [[ 
    "$dir_name" == "main" ||
    "$dir_name" == "mobilka" ||
    "$dir_name" == "web-1" ]]

}

# Loop through each directory
for dir in "$parent_dir"/*; do
  # Check if the directory is indeed a directory
  if [ -d "$dir" ] && is_app_dir "$(basename "$dir")"; then
    # Enter the directory
    cd "$dir" || continue

    # Execute the command
    echo "Executing 'git checkout master && git add . && git commit -m "update" && git push' in $(pwd)"
    git checkout master && git add . && git commit -m "update" && git push

    # Return to the original directory
    cd ..
  fi
done

git add .
git commit -m "Updating subrepos... $(date +"%D %T")"
echo "Updating subrepos... $(date +"%D %T")"
git push

echo 'Push OK'
