#! /bin/bash

start=$(date +%s.%N)

script_dir=$(dirname "$(dirname "$(realpath "$0")")")

cd "$script_dir" || (echo "FAILED" && exit)

echo "You are in:"
pwd

find . -type f -exec chmod -v +x {} \;

cd ".." || (echo "FAILED" && exit)

echo "You are in:"
pwd
echo ""
echo ""
echo "CHMOD in progres, waiting..."
echo ""
if command -v sudo &>/dev/null; then
  echo "USING SUDO"
  find . -type d -name "node_modules" -exec sudo chmod -R 777 {} \;
else
  echo "SUDO NOT FOUND"
  find . -type d -name "node_modules" -exec chmod -R 777 {} \;
fi


echo 'CHMOD OK'

end=$(date +%s.%N)
runtime=$(echo "$end - $start" | bc)
echo "CHMOD Elapsed time: ${runtime} seconds"
