#! /bin/bash

start=$(date +%s.%N)

# Define the command to execute
command="yarn"

script_dir=$(dirname "$(realpath "$0")")

# Go up two levels
parent_dir=$(dirname "$(dirname "$script_dir")")

is_app_dir() {
  local dir_name="$1"
  [[ 
    "$dir_name" == "main" ||
    "$dir_name" == "mobilka" ||
    "$dir_name" == "web-1" ||
    "$dir_name" == "web-2" ]]

}

# Loop through each directory
for dir in "$parent_dir"/*; do
  # Check if the directory is indeed a directory
  if [ -d "$dir" ] && is_app_dir "$(basename "$dir")"; then
    # Enter the directory
    cd "$dir" || continue

    # Execute the command
    echo "Executing '$command' in $(pwd)"
    $command

    # Return to the original directory
    cd ..
  fi
done

bash "$script_dir"/../cp-kernel

echo 'Install OK, CP-KERNEL OK.'

end=$(date +%s.%N)
runtime=$(echo "$end - $start" | bc)
echo "INSTALL-DEV Elapsed time: ${runtime} seconds"
